---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: vaccination-system-dev
  labels:
    svc: vms
spec:
  type: ClusterIP
  selector:
    vms: appointment
  ports:
  - name: web
    protocol: TCP
    port: 8001
    targetPort: 19090

